In [1]:
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point
from geopy.distance import geodesic

In [2]:
january_df = pd.read_csv("Resources/JC-202401-citibike-tripdata.csv")
january_df = january_df.dropna()
january_df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,0744109F13385D1D,electric_bike,2024-01-15 15:18:07,2024-01-15 15:32:44,Morris Canal,JC072,Oakland Ave,JC022,40.712297,-74.038185,40.737604,-74.052478,member
1,B1488BFEF9118000,classic_bike,2024-01-13 15:32:50,2024-01-13 15:36:18,JC Medical Center,JC110,Grove St PATH,JC115,40.715391,-74.049692,40.719410,-74.043090,member
2,95A2FE8E51B4C836,classic_bike,2024-01-19 13:11:00,2024-01-19 13:14:44,Morris Canal,JC072,Exchange Pl,JC116,40.712419,-74.038526,40.716366,-74.034344,member
3,95D9AFF6A1652DC1,classic_bike,2024-01-23 07:03:49,2024-01-23 07:07:11,Morris Canal,JC072,Exchange Pl,JC116,40.712419,-74.038526,40.716366,-74.034344,member
4,5F7408988A83B1B3,classic_bike,2024-01-01 16:46:10,2024-01-01 16:50:31,Morris Canal,JC072,Harborside,JC104,40.712419,-74.038526,40.719252,-74.034234,member

In [ ]:
july_df = pd.read_csv("Resources/JC-202407-citibike-tripdata.csv")
july_df = july_df.dropna()
july_df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,6B61E4880B1DE1E9,electric_bike,2024-07-31 12:06:49.628,2024-07-31 12:23:59.876,14 St Ferry - 14 St & Shipyard Ln,HB202,Brunswick & 6th,JC081,40.752961,-74.024353,40.726012,-74.050389,member
1,B593705A700E04B9,electric_bike,2024-07-01 07:53:20.019,2024-07-01 08:13:56.570,Leonard Gordon Park,JC080,McGinley Square,JC055,40.745717,-74.057247,40.725340,-74.067622,member
2,19CFBBAF90BF45B8,electric_bike,2024-07-30 14:57:29.219,2024-07-30 15:10:49.553,Liberty Light Rail,JC052,Hoboken Ave at Monmouth St,JC105,40.711242,-74.055701,40.735208,-74.046964,casual
3,8E6563C41AA8A1B4,electric_bike,2024-07-17 17:02:20.147,2024-07-17 17:04:50.818,Grand St & 14 St,HB506,Madison St & 10 St,HB503,40.754090,-74.031600,40.749943,-74.035865,member
4,44065C7E4AE573FA,electric_bike,2024-07-20 17:19:44.970,2024-07-20 17:39:09.894,Hoboken Terminal - River St & Hudson Pl,HB102,Madison St & 10 St,HB503,40.736068,-74.029127,40.749943,-74.035865,casual

In [5]:
def calculate_distance(row):
    start = (row['start_lat'], row['start_lng'])
    end = (row['end_lat'], row['end_lng'])
    return geodesic(start, end).kilometers

In [6]:
january_df['distance_km'] = january_df.apply(calculate_distance, axis=1)
january_df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,distance_km
0,0744109F13385D1D,electric_bike,2024-01-15 15:18:07,2024-01-15 15:32:44,Morris Canal,JC072,Oakland Ave,JC022,40.712297,-74.038185,40.737604,-74.052478,member,3.058765
1,B1488BFEF9118000,classic_bike,2024-01-13 15:32:50,2024-01-13 15:36:18,JC Medical Center,JC110,Grove St PATH,JC115,40.715391,-74.049692,40.719410,-74.043090,member,0.714354
2,95A2FE8E51B4C836,classic_bike,2024-01-19 13:11:00,2024-01-19 13:14:44,Morris Canal,JC072,Exchange Pl,JC116,40.712419,-74.038526,40.716366,-74.034344,member,0.563001
3,95D9AFF6A1652DC1,classic_bike,2024-01-23 07:03:49,2024-01-23 07:07:11,Morris Canal,JC072,Exchange Pl,JC116,40.712419,-74.038526,40.716366,-74.034344,member,0.563001
4,5F7408988A83B1B3,classic_bike,2024-01-01 16:46:10,2024-01-01 16:50:31,Morris Canal,JC072,Harborside,JC104,40.712419,-74.038526,40.719252,-74.034234,member,0.840973

In [7]:
july_df['distance_km'] = july_df.apply(calculate_distance, axis=1)
july_df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,distance_km
0,6B61E4880B1DE1E9,electric_bike,2024-07-31 12:06:49.628,2024-07-31 12:23:59.876,14 St Ferry - 14 St & Shipyard Ln,HB202,Brunswick & 6th,JC081,40.752961,-74.024353,40.726012,-74.050389,member,3.713791
1,B593705A700E04B9,electric_bike,2024-07-01 07:53:20.019,2024-07-01 08:13:56.570,Leonard Gordon Park,JC080,McGinley Square,JC055,40.745717,-74.057247,40.725340,-74.067622,member,2.426682
2,19CFBBAF90BF45B8,electric_bike,2024-07-30 14:57:29.219,2024-07-30 15:10:49.553,Liberty Light Rail,JC052,Hoboken Ave at Monmouth St,JC105,40.711242,-74.055701,40.735208,-74.046964,casual,2.761881
3,8E6563C41AA8A1B4,electric_bike,2024-07-17 17:02:20.147,2024-07-17 17:04:50.818,Grand St & 14 St,HB506,Madison St & 10 St,HB503,40.754090,-74.031600,40.749943,-74.035865,member,0.584609
4,44065C7E4AE573FA,electric_bike,2024-07-20 17:19:44.970,2024-07-20 17:39:09.894,Hoboken Terminal - River St & Hudson Pl,HB102,Madison St & 10 St,HB503,40.736068,-74.029127,40.749943,-74.035865,casual,1.642598

In [20]:
january_df.to_csv("january_data.csv", index=False)

In [21]:
july_df.to_csv("july_data.csv", index=False)

In [10]:
full_df = pd.concat([january_df, july_df], ignore_index=True)
full_df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,distance_km
0,0744109F13385D1D,electric_bike,2024-01-15 15:18:07,2024-01-15 15:32:44,Morris Canal,JC072,Oakland Ave,JC022,40.712297,-74.038185,40.737604,-74.052478,member,3.058765
1,B1488BFEF9118000,classic_bike,2024-01-13 15:32:50,2024-01-13 15:36:18,JC Medical Center,JC110,Grove St PATH,JC115,40.715391,-74.049692,40.719410,-74.043090,member,0.714354
2,95A2FE8E51B4C836,classic_bike,2024-01-19 13:11:00,2024-01-19 13:14:44,Morris Canal,JC072,Exchange Pl,JC116,40.712419,-74.038526,40.716366,-74.034344,member,0.563001
3,95D9AFF6A1652DC1,classic_bike,2024-01-23 07:03:49,2024-01-23 07:07:11,Morris Canal,JC072,Exchange Pl,JC116,40.712419,-74.038526,40.716366,-74.034344,member,0.563001
4,5F7408988A83B1B3,classic_bike,2024-01-01 16:46:10,2024-01-01 16:50:31,Morris Canal,JC072,Harborside,JC104,40.712419,-74.038526,40.719252,-74.034234,member,0.840973

In [11]:
full_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 162459 entries, 0 to 162458
Data columns (total 14 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             162459 non-null  object
 1   rideable_type       162459 non-null  object
 2   started_at          162459 non-null  object
 3   ended_at            162459 non-null  object
 4   start_station_name  162459 non-null  object
 5   start_station_id    162459 non-null  object
 6   end_station_name    162459 non-null  object
 7   end_station_id      162459 non-null  object
 8   start_lat           162459 non-null  float64
 9   start_lng           162459 non-null  float64
 10  end_lat             162459 non-null  float64
 11  end_lng             162459 non-null  float64
 12  member_casual       162459 non-null  object
 13  distance_km         162459 non-null  float64
dtypes: float64(5), object(9)
memory usage: 17.4+ MB

In [ ]:
full_df['geometry'] = full_df.apply(lambda row: Point(row['start_lng'], row['start_lat']), axis=1)

gdf = gpd.GeoDataFrame(full_df, geometry='geometry')

# Load the GeoJSON or shapefile with zip code boundaries
zip_codes = gpd.read_file("Resources/jerseycityzipcodegeojson.geojson")
# zip_codes.head()

# Ensure both GeoDataFrames use the same coordinate reference system (CRS)
gdf = gdf.set_crs(zip_codes.crs, allow_override=True)

# Perform the spatial join
gdf_with_zip = gpd.sjoin(gdf, zip_codes[['zcta5ce10', 'geometry']], how='left', op='within')
gdf_with_zip = gdf_with_zip.rename(columns={"zcta5ce10": "zip_code"}).drop(columns=["index_right"])

# Convert back to a regular DataFrame
df_with_zip = pd.DataFrame(gdf_with_zip.drop(columns="geometry"))
df_with_zip.head()

c:\Users\willi\anaconda3\envs\dev\lib\site-packages\IPython\core\interactiveshell.py:3517: FutureWarning: The `op` parameter is deprecated and will be removed in a future release. Please use the `predicate` parameter instead.
  if await self.run_code(code, result, async_=asy):

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,distance_km,zip_code
0,0744109F13385D1D,electric_bike,2024-01-15 15:18:07,2024-01-15 15:32:44,Morris Canal,JC072,Oakland Ave,JC022,40.712297,-74.038185,40.737604,-74.052478,member,3.058765,07302
1,B1488BFEF9118000,classic_bike,2024-01-13 15:32:50,2024-01-13 15:36:18,JC Medical Center,JC110,Grove St PATH,JC115,40.715391,-74.049692,40.719410,-74.043090,member,0.714354,07302
2,95A2FE8E51B4C836,classic_bike,2024-01-19 13:11:00,2024-01-19 13:14:44,Morris Canal,JC072,Exchange Pl,JC116,40.712419,-74.038526,40.716366,-74.034344,member,0.563001,07302
3,95D9AFF6A1652DC1,classic_bike,2024-01-23 07:03:49,2024-01-23 07:07:11,Morris Canal,JC072,Exchange Pl,JC116,40.712419,-74.038526,40.716366,-74.034344,member,0.563001,07302
4,5F7408988A83B1B3,classic_bike,2024-01-01 16:46:10,2024-01-01 16:50:31,Morris Canal,JC072,Harborside,JC104,40.712419,-74.038526,40.719252,-74.034234,member,0.840973,07302

In [18]:
df_with_zip.info()

<class 'pandas.core.frame.DataFrame'>
Index: 162459 entries, 0 to 162458
Data columns (total 15 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             162459 non-null  object
 1   rideable_type       162459 non-null  object
 2   started_at          162459 non-null  object
 3   ended_at            162459 non-null  object
 4   start_station_name  162459 non-null  object
 5   start_station_id    162459 non-null  object
 6   end_station_name    162459 non-null  object
 7   end_station_id      162459 non-null  object
 8   start_lat           162459 non-null  float64
 9   start_lng           162459 non-null  float64
 10  end_lat             162459 non-null  float64
 11  end_lng             162459 non-null  float64
 12  member_casual       162459 non-null  object
 13  distance_km         162459 non-null  float64
 14  zip_code            87375 non-null   object
dtypes: float64(5), object(10)
memory usage: 19.8+ MB

In [19]:
df_with_zip.to_csv("stacked_data.csv", index=False)